definition:
  id: 'obscsr-medbpot-002'
  action: 'finetune'
  llm: 'llama3'
  get_from: 's3'
qlora_params: 
  Rank: 1
  Alpha: 0.5
general_ft_params: 
  batch_size: 32
  lr: 0.001
  epochs: 10
training_material:
  training_dataset: "name"
  validation_dataset: "name"